"""Turning a graph node into a batch script.

The script is a header carrier, not generated code. Its body is one line that
calls back into ACKBAR, so the task itself is python that can be tested without
a scheduler, and so that the only thing the emitter has to get right is the
`#SBATCH` block.

Scripts are written once, at create time, for every cycle. That costs a few
hundred small files and buys two things: `sacct` stores the script it ran
(`AccountingStoreFlags=job_script`), and "what exactly did cycle 7's forecast
run" is answered by reading a file rather than by reconstructing a command line.

Two things are deliberately *not* in the script: `--array` and `--dependency`.
Those are the two values that differ between a first attempt and a healed one,
so they belong on the `sbatch` command line, where a heal can change them
without rewriting history.
"""

import os
import stat
import sys

#: Written into every script, so a job's environment comes from the site file
#: rather than from whichever shell happened to submit it. v2 used environment
#: variables as the interface between steps, and that is exactly the failure
#: mode: a job that only works when submitted from the right terminal.
#:
#: `set -e` comes *after* the source, not before. `activate.sh` pulls in the
#: machine's toolchain setup, and spack's own shell code is not written to
#: survive `set -u`. Guarding ACKBAR's lines is the point; failing inside
#: somebody else's is not.
#: The stack limit is here rather than in a site file because it is an
#: assumption of the coupled model rather than of a machine: FMS puts large
#: automatic arrays on the stack, v2 set this on every machine including its
#: default, and FMS's own test harness refuses to run without it. Slurm gives a
#: job whatever `RLIMIT_STACK` the slurmd inherited, so unset this presents as
#: an unreproducible segfault at a resolution change rather than as a
#: configuration error. `|| true` because a hard limit below unlimited makes
#: this fail, and a job that can still run under the inherited limit should.
PREAMBLE = """\
export ACKBAR_ROOT={root}
source "$ACKBAR_ROOT/site/activate.sh"
set -euo pipefail
ulimit -s unlimited || true
"""


def resource_flags(resources):
    """`#SBATCH` lines for one task's resources.

    Nothing is defaulted here. A task with no entry and no `default` in the
    domain layer is caught by `validate` step 6, because inheriting sbatch's own
    defaults means one core and the site's `DefMemPerCPU`, which is a silent
    wrong answer rather than an error.
    """
    lines = []
    if "ntasks" in resources:
        lines.append(f"#SBATCH --ntasks={resources['ntasks']}")
    if "time" in resources:
        lines.append(f"#SBATCH --time={resources['time']}")
    if "mem" in resources:
        lines.append(f"#SBATCH --mem={resources['mem']}")
    return lines


def job_name(experiment, cycle, task):
    """`<exp>.<cycle>.<task>`, with the array index carrying the member.

    The experiment name is part of the identity because running several at once
    is the entire point of the project. Without it `sacct --name` attributes
    rows to the wrong experiment and `--dependency=singleton` silently couples
    unrelated ones.
    """
    return f"{experiment}.{cycle}.{task}"


def comment(experiment, cycle, task):
    """The second copy of the identity, the one that survives into accounting.

    Comes back as a structured field from `sacct --json` where
    `AccountingStoreFlags` includes `job_comment`, so a harvested row maps to
    cycle, task and member without a side table.
    """
    return f"ackbar:{experiment}:{cycle}:{task}"


def script_text(config, paths, node, *, root, python):
    """The whole batch script for one node."""
    experiment = paths.experiment
    lines = ["#!/bin/bash"]
    lines.append(f"#SBATCH --job-name={job_name(experiment, node.cycle, node.task)}")
    lines.append(f"#SBATCH --comment={comment(experiment, node.cycle, node.task)}")
    lines.append(f"#SBATCH --output={paths.job_log(node.cycle, node.task, node.is_array)}")
    lines.append("#SBATCH --open-mode=append")
    lines.extend(resource_flags(node.resources))

    if node.task == "submit":
        # Requeue reruns a batch script from its beginning, and a requeued
        # submitter submits a whole cycle twice. See the marker in paths.py:
        # this is one of the three protections, and none of them stands alone.
        lines.append("#SBATCH --no-requeue")

    lines.append("")
    lines.append(f"# {node.task}: generated by ackbar, do not edit.")
    lines.append(PREAMBLE.format(root=root).rstrip())
    lines.append("")

    member = '"${SLURM_ARRAY_TASK_ID}"' if node.is_array else ""
    invocation = [
        f'exec "{python}" -m ackbar.cli run {experiment}',
        f"--cycle {node.cycle}",
        f"--task {node.task}",
    ]
    if member:
        invocation.append(f"--member {member}")
    lines.append(" \\\n    ".join(invocation))
    return "\n".join(lines) + "\n"


def write_script(config, paths, node, *, root, python):
    """Emit one node's script.

    Deliberately *not* the log directory. Slurm opens `--output` before the job
    script runs and will not create the path, so it has to exist before
    `sbatch`, which is where `submit` now makes it. Making it here instead meant
    `ackbar create` laid down `run/<date>/log/` for every cycle of the
    experiment at once, so a sixty cycle run showed sixty run directories before
    it had run anything, fifty nine of them holding one empty directory. What
    someone reads the tree of a running experiment *for* is which cycles have
    happened.
    """
    target = paths.job_script(node.cycle, node.task)
    target.parent.mkdir(parents=True, exist_ok=True)
    # By rename, like every other artifact: an interrupted `create` otherwise
    # leaves a truncated job script that looks finished, and `create` writes
    # every cycle's scripts up front so there are a lot of chances.
    temp = target.with_name(target.name + ".partial")
    temp.write_text(script_text(config, paths, node, root=root, python=python))
    temp.chmod(temp.stat().st_mode | stat.S_IXUSR)
    temp.replace(target)
    return target


def write_all(config, paths, graph, *, root, python=None):
    """Every node in the graph. Returns the paths written, in graph order."""
    python = python or sys.executable
    root = os.fspath(root)
    written = []
    for node_id in graph.order():
        node = graph.get(*_split(node_id))
        written.append(write_script(config, paths, node, root=root, python=python))
    return written


def _split(node_id):
    cycle, _, task = node_id.partition(".")
    return int(cycle), task
