"""Stochastic physics: what makes one member's model differ from another's.

An ensemble whose members share one model and one atmosphere has only the
spread its initial condition arrived with, and a filter that assimilates every
cycle takes that spread away faster than a free forecast puts it back. This is
one of the ways to put it back, and the only one that needs nothing downloaded.

**One scheme, oSPPT.** It scales the whole diabatic tendency:
`MOM_diabatic_driver.F90` replaces the change a timestep made in thickness,
temperature and salinity with that change times a random field centred on one.
Measured on `gom_25km`, that reaches surface temperature and the mixed layer,
adds about a tenth of a degree of surface temperature spread per cycle, and does
nothing at all for sea surface height or salinity: over a day the diabatic
change in column mass and in salt is too small for a multiplier to move.

**MOM6's interface carries two more schemes and ACKBAR carries neither.**

`PERT_EPBL` perturbs the boundary layer's TKE generation and dissipation
separately, inside `MOM_energetic_PBL.F90`, which is the right *place* for mixed
layer spread. It was implemented, measured and removed. The perturbation is
real: `epbl1_wts` and `epbl2_wts` come out with standard deviations of 0.32 and
0.24 around one, so the TKE budget is being scaled by about a third. It moved
surface temperature spread by 2% and the column not at all, both as free
forecasts from a common state and as a cycle of the LETKF's own ensemble. Under
an NCAR normal-year climatology the wind is smooth and the July Gulf mixed layer
is set by the imposed fluxes and the stratification rather than by the closure's
efficiency. Worth trying again *only* once ensemble atmospheric forcing exists,
and adding it back is one entry in `_SCHEMES` plus a schema block.

`DO_SKEB` crashes inside `MOM_neutral_diffusion` on this domain at every
amplitude tried, down to a fortieth of the one that first failed. An error that
does not soften with amplitude is not a CFL limit to tune around.

**MOM6 reads the switches and does not own the pattern.** The random field is
generated by NOAA-PSL/stochastic_physics, vendored at `pkg/stochastic_physics`
and compiled into `coupler_main`; it reads its own `&nam_stochy` group out of
`input.nml`, which no MOM6 parameter file can carry. Both halves have to agree.
`DO_SPPT` turns the application on inside MOM6, `ocnsppt` turns the pattern on
inside the generator, and `init_stochastic_physics_ocn` fails the run when they
disagree rather than quietly applying a pattern of zeros. That is why one call
here produces both.

**The seed is a function of the member and the cycle and of nothing else.**
Three things follow from that and each is a decision:

* Not the clock. `iseed = 0` means "use the system clock" to the generator, and
  a healed forecast would then integrate a different trajectory from the one the
  failed attempt was producing, which makes an experiment unreproducible in
  exactly the case where reproducing it matters.
* Not the task. The cycling forecast and the extended forecast start from the
  same state, and different seeds would make the long forecast's first day a
  different trajectory from the cycle it is meant to continue.
* Not the layer. The seed comes out of `ensemble.stochastic.seed` in the frozen
  `cfg/`, so two experiments that want independent draws say so by differing
  there, and rerunning one reproduces it.

**Every cycle draws a fresh pattern.** The generator can read a saved pattern
back (`stochini`), but the only reader is the atmosphere's and there is no
writer for the ocean's at all, so a cycle's pattern starts from its seed rather
than continuing the last cycle's. With a timescale well inside a cycle that is
not a loss: the pattern is initialized at its stationary variance, not at zero.
"""

from .duration import parse_duration

#: The schemes, and the three names each one is: the MOM6 parameter that turns
#: the application on, the generator's prefix for amplitude, length scale and
#: timescale, and its seed key. A dict of one, because a second scheme would be
#: a line here and the rest of this module already reads it as a set.
_SCHEMES = {
    "sppt": ("DO_SPPT", "ocnsppt", "iseed_ocnsppt"),
}

#: The last digit of a seed, so two schemes in one member could never draw the
#: same pattern. Kept with one scheme because it is part of what a seed *is*:
#: dropping it would renumber every seed, so an experiment rerun after the
#: change would not reproduce the one before it.
_OFFSET = {"sppt": 0}

#: How many members and cycles the seed encodes. A member number is three
#: digits because `mem###` is, and five digits of cycle is a century of daily
#: cycling. The whole seed stays well inside the `integer(8)` the generator
#: declares as long as `ensemble.stochastic.seed` obeys its schema bound.
_MEMBERS = 1000
_CYCLES = 100000


class StochasticError(ValueError):
    pass


def settings(config):
    """The `ensemble.stochastic` block, or None when the experiment has none.

    None is the answer for every experiment written before this existed and for
    every one that does not want it, and it has to reach the model as "write
    nothing": the executable is the same either way, and a run with no
    `&nam_stochy` group and no `DO_SPPT` reproduces a run built without the
    generator at all, bit for bit.
    """
    return (config.get("ensemble") or {}).get("stochastic")


def perturbs(member):
    """Whether *member*'s forecast is perturbed.

    Every member but the control, which is `mem000`. The control is what the
    experiment is scored on and what a variational experiment is compared
    against, so perturbing it would put noise into the answer rather than into
    the covariance. It is also the member an LETKF writes the posterior mean
    into, and a mean is not a draw.
    """
    return member is not None and member != 0


def parameters(stochastic):
    """The MOM6 parameter file that turns the application on.

    A third file rather than lines in `MOM_override`, because the override is
    the domain's and is read by SOCA as well: SOCA builds its geometry from the
    same parameter files, and its MOM6 is a different one that has no
    generator behind the interface. This file is the forecast's alone.

    No `#override`: neither `MOM_input` nor `MOM_override` sets these, so they
    arrive as new parameters, and `#override` on an unset parameter is a fatal
    of its own.
    """
    lines = ["! written by ackbar from ensemble.stochastic"]
    for name, (switch, _, _) in _SCHEMES.items():
        # The same test `namelist` makes, and it has to be: a scheme switched on
        # in one file and absent from the other is what
        # `init_stochastic_physics_ocn` refuses the run over. `in` here against
        # a truth test there would disagree over an empty scheme, which the
        # schema rejects today and is one `required:` away from not rejecting.
        if stochastic.get(name):
            lines.append(f"{switch} = True")
    return "\n".join(lines) + "\n"


def namelist(stochastic, member, cycle):
    """The `&nam_stochy` group, for appending to `input.nml`.

    Appended rather than patched in: no base case has the group, and a namelist
    reader ignores groups it was not asked for, so it costs nothing in a run
    that is not perturbed except that ACKBAR does not write it then either.

    The amplitude, length scale and timescale are scalars assigned to arrays of
    five, which sets the first element and leaves the rest at the generator's
    "unset". One pattern per scheme is what the schema allows and what the
    spread measurements were made with.

    The values NOAA-PSL runs oSPPT at, for reference when reading an
    experiment's own: amplitude 0.8, length scale 500 km, timescale 6 hours
    (`NOAA-PSL/NestedReplay`, and the same length scale and timescale in JCSDA's
    UFS-marine quarter degree namelist). Those are global configurations, so the
    length scale in particular deserves a second thought on a basin that is only
    a few of them across.

    `amplitude` is the pattern's standard deviation and not the multiplier's.
    `run_stochastic_physics_ocn` maps the pattern through `2 / (1 + exp(-x))`,
    which carries the real line into `(0, 2)`, so the multiplier is bounded by
    construction rather than clipped, and its mean is one because the transform
    is odd-symmetric about `(0, 1)`. Near one it is `1 + x/2`, so what the model
    applies has about half the spread asked for here, and less than half as the
    logistic saturates.
    """
    # `length_scale` is an e-folding length in metres, and this line is what
    # makes it one. `setvarspect` in `stochy_patterngenerator.F90` carries two
    # variance spectra: the generator's default puts `L**2 / 4` in the exponent
    # and `new_lscale` puts `(L / 4)**2`, four times smaller, which its own
    # comment calls "fix for proper lengthscale". Under the default a pattern is
    # twice as wide as the number asks for, which on a basin a few length scales
    # across is the difference between a field of errors and one multiplier with
    # a gradient. Written unconditionally rather than exposed: a key called
    # `length_scale` in metres has one correct meaning, and letting an
    # experiment choose between two of them records a number that does not say
    # what it is.
    lines = ["&nam_stochy", "  new_lscale = .true."]
    for name, (_, amp, seed_key) in _SCHEMES.items():
        scheme = stochastic.get(name)
        if not scheme:
            continue
        tau = parse_duration(scheme["timescale"]).total_seconds()
        lines.append(f"  {amp} = {float(scheme['amplitude'])}")
        lines.append(f"  {amp}_lscale = {float(scheme['length_scale'])}")
        lines.append(f"  {amp}_tau = {tau}")
        lines.append(f"  {seed_key} = {seed(stochastic['seed'], member, cycle, name)}")
    lines.append("/")
    return "\n".join(lines) + "\n"


def seed(base, member, cycle, scheme):
    """This member's seed for this cycle's draw of *scheme*.

    Positive by construction, because zero is the generator's word for "ask the
    clock" and the whole point of this function is that nothing asks the clock.
    """
    if member is None or not 0 <= member < _MEMBERS:
        raise StochasticError(
            f"member {member} cannot be seeded: the seed encodes a member "
            f"number under {_MEMBERS}, which is what `mem###` can name"
        )
    if not 0 <= cycle < _CYCLES:
        raise StochasticError(
            f"cycle {cycle} cannot be seeded: the seed encodes a cycle number "
            f"under {_CYCLES}"
        )
    return ((base * _MEMBERS + member) * _CYCLES + cycle) * 10 + _OFFSET[scheme]
